spring:
  application:
    name: lab_1
  server:
    port: 8080
  datasource:
    url: jdbc:postgresql://localhost:5432/lab_1
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
