apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-activemq
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-activemq
    spec:
      containers:
        - name: activemq
          image: apache/activemq-classic:6.1.6
          ports:
            - containerPort: 61616
            - containerPort: 61613
---
apiVersion: v1
kind: Service
metadata:
  name: activemq
spec:
  selector:
    app: {{ .Release.Name }}-activemq
  ports:
    - name: openwire
      port: 61616
      targetPort: 61616
    - name: stomp
      port: 61613
      targetPort: 61613
