apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-spring-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Release.Name }}-vault-backend
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-spring-secret
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: blps/spring
        property: DB_PASSWORD
    - secretKey: INSTANCE_NUM
      remoteRef:
        key: blps/spring
        property: INSTANCE_NUM