apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-spring-config
data:
  SERVER_PORT: {{ .Values.server.port | quote }}
  DB_HOST: {{ .Values.db.host | quote }}
  DB_PORT: {{ .Values.db.port | quote }}
  DB_NAME: {{ .Values.postgresql.auth.database | quote }}
  DB_USERNAME: {{ .Values.postgresql.auth.username | quote }}
  DDL_AUTO: {{ .Values.db.ddlAuto | quote }}
  SQL_INIT_MODE: {{ .Values.db.sqlInitMode | quote }}
  ACTIVEMQ_HOST: {{ .Values.activemq.host | quote }}
  ACTIVEMQ_STOMP_PORT: {{ .Values.activemq.stompPort | quote }}
  ACTIVEMQ_BROKER_URL: {{ .Values.activemq.brokerUrl | quote }}
  ACTIVEMQ_QUEUE: {{ .Values.activemq.queue | quote }}
